#docker-compose:
version: '3.8'

services:
    rabbitmq-banca:
        image: rabbitmq:4.0-management
        container_name: rabbitmq-banca
        hostname: rabbitmq-banca
        restart: always
        ports:
        - 5673:5672
        - 15673:15672
        networks:
            - bancanet
        
    mysql-banca:
        image: imgmysql
        container_name: mysql-banca
        hostname: mysql-banca
        restart: always
        ports:
            - "3307:3306"
        networks:
            - bancanet
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./mysql/varlibmysql:/docker-entrypoint-initdb.d
            
    mongodb-banca:
        image: mongo:latest
        container_name: mongodb-banca
        hostname: mongodb-banca
        restart: always
        ports:
            - "27018:27017"
        networks:
            - bancanet

    msclientes:
        image: imgclientes
        container_name: msclientes
        hostname: msclientes
        networks:
            - bancanet
        ports:
            - "8081:8081"
        environment:
            - DB_HOSTNAME=mysql-banca
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - API_REPORTES=http://msreportes:8083/api/reporte
        restart: always
        depends_on:
            - mysql-banca
    
    mscuentas:
        image: imgcuentas
        container_name: mscuentas
        hostname: mscuentas
        networks:
            - bancanet
        ports:
            - "8082:8082"
        environment:
            - DB_HOSTNAME=mysql-banca
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - API_CLIENTES=http://msclientes:8081/api/clientes
        restart: always
        depends_on:
            - mysql-banca
            - rabbitmq-banca
            - msclientes
    
    msreportes:
        image: imgreportes
        container_name: msreportes
        hostname: msreportes
        networks:
            - bancanet
        ports:
            - "8083:8083"
        environment:
            - MONGO_URI=mongodb://mongodb-banca:27017/reportes
        restart: always
        depends_on:
            - mongodb-banca
            - rabbitmq-banca
            - mscuentas

networks:
    bancanet:
        external: true