#Dockerfile db cuentas-bancarias
FROM mysql:8.0

LABEL maintainer "javaedi.et@gmail.com"
LABEL description "base de datos para cuentas bancarias"

ENV MYSQL_ROOT_PASSWORD=secret

EXPOSE 3306

CMD ["mysqld"]